apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  MYSQL_PASSWORD: QXV0aDEyMw==  # Base64-encoded value for 'Auth123'
  JWT_SECRET: YXBhbWJhbmk=      # Base64-encoded value for 'apambani'
